version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mahidol888-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/production.db
      - SESSION_SECRET=${SESSION_SECRET:-your-super-secret-session-key-change-this}
      - CSRF_SECRET=${CSRF_SECRET:-your-super-secret-csrf-key-change-this}
      - ENABLE_RATE_LIMITING=true
      - MAX_LOGIN_ATTEMPTS=5
      - MAX_BET_ATTEMPTS=10
      - PUBLIC_SITE_URL=${PUBLIC_SITE_URL:-http://localhost:3000}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-}
    volumes:
      - app_data:/app/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/csrf']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: mahidol888-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app-network
    profiles:
      - production

volumes:
  app_data:
    driver: local

networks:
  app-network:
    driver: bridge
